noinst_LTLIBRARIES = libmcslv.la

libmcslv_la_SOURCES = \
	slv.h \
	slv_internal.h \
	slv_expr.c \
	slv_parser.c \
	slv_eval.c \
	slv_format.c \
	slv_reader.c \
	slv_reader.h \
	slv_load.c \
	slv_load.h \
	slv_edit.c \
	slv_edit.h
libmcslv_la_CPPFLAGS = \
	$(GLIB_CFLAGS) \
	-I$(top_srcdir) \
	-DMC_PLUGIN_DIR=\"$(panel_plugins_dir)/mcstruct\"
libmcslv_la_LIBADD = $(GLIB_LIBS) -lm

mcstructdir = $(panel_plugins_dir)/mcstruct
mcstruct_LTLIBRARIES = mc-panel-mcstruct.la
dist_mcstruct_DATA = mcstruct_panel.hlp

mc_panel_mcstruct_la_SOURCES = \
	mcstruct.c \
	mcstruct_ui.c \
	mcstruct_ui_priv.h \
	mcstruct_grid.c \
	mcstruct_cmd.c \
	mcstruct_bytes.c \
	mcstruct_layout.c \
	mcstruct_ui.h
mc_panel_mcstruct_la_CPPFLAGS = \
	$(GLIB_CFLAGS) \
	-I$(top_srcdir) \
	-DMC_PLUGIN_DIR=\"$(panel_plugins_dir)/mcstruct\"
mc_panel_mcstruct_la_LDFLAGS = -module -avoid-version
mc_panel_mcstruct_la_LIBADD = libmcslv.la $(GLIB_LIBS)

mcstructdatadir = $(panel_plugins_dir)/mcstruct/data
dist_mcstructdata_DATA = \
	data/mcstruct.ini \
	data/stl.als \
	data/zip.stl \
	data/exe.stl \
	data/dbf.stl \
	data/elf.stl \
	data/mbr.stl \
	data/fat_boot.stl \
	data/uimage.stl \
	data/dtb.stl \
	data/png.stl \
	data/bmp.stl \
	data/wav.stl \
	data/sqlite.stl \
	data/gif.stl \
	data/ico.stl \
	data/gzip.stl \
	data/pcap.stl \
	data/cpio_old.stl \
	data/tga.stl \
	data/pcx.stl \
	data/au.stl \
	data/ines.stl \
	data/gpt.stl \
	data/edid.stl \
	data/id3v1.stl \
	data/wad.stl \
	data/pak.stl \
	data/mo.stl \
	data/utmp.stl \
	data/midi.stl \
	data/cramfs.stl \
	data/lzh.stl \
	data/voc.stl \
	data/ivf.stl \
	data/tim.stl \
	data/xwd.stl \
	data/mdl.stl \
	data/trx.stl \
	data/sparse.stl \
	data/android_img.stl \
	data/hashcat_restore.stl \
	data/aix_utmp.stl \
	data/ether.stl \
	data/dns.stl \
	data/ssh_pubkey.stl \
	data/homm_bmp.stl \
	data/respack.stl \
	data/andes_fw.stl \
	data/dcx.stl \
	data/chg.stl \
	data/ftl_dat.stl \
	data/nanoapp.stl \
	data/homm_agg.stl \
	data/systemtime.stl \
	data/dune2_pak.stl \
	data/macho_fat.stl \
	data/gt_vol.stl \
	data/hccap.stl \
	data/stl3d.stl \
	data/asus_bootldr.stl \
	data/fallout_dat.stl \
	data/fallout2_dat.stl \
	data/avantes_roh60.stl \
	data/glb.stl \
	data/rtp.stl \
	data/heaps_pak.stl \
	data/zisofs.stl \
	data/icmp.stl \
	data/android_dto.stl \
	data/luks.stl \
	data/glshaders.stl \
	data/amlogic_mpt.stl \
	data/shx.stl \
	data/tsm.stl \
	data/op2.stl \
	data/vmdk.stl \
	data/zx_tap.stl \
	data/shell_items.stl \
	data/nt_mdt_pal.stl \
	data/vpp.stl \
	data/websocket.stl \
	data/hccapx.stl \
	data/huawei_bootldr.stl \
	data/apm.stl \
	data/ogg.stl \
	data/chrome_pak.stl \
	data/dime.stl \
	data/sudoers_ts.stl \
	data/mar.stl \
	data/xar.stl \
	data/gbr.stl \
	data/applesd.stl \
	data/tls_hello.stl \
	data/pff2.stl \
	data/id3v2.stl \
	data/cfb.stl \
	data/bitcoin_tx.stl \
	data/avi.stl \
	data/winres.stl \
	data/trdos.stl \
	data/efi_siglist.stl \
	data/pif.stl \
	data/lvm2.stl \
	data/rar.stl \
	data/btrfs_stream.stl \
	data/allegro_dat.stl \
	data/qcom_bootldr.stl \
	data/blend.stl \
	data/vox.stl \
	data/android_super.stl \
	data/journal.stl \
	data/swf.stl \
	data/uefi_te.stl \
	data/vdi.stl \
	data/lnk.stl \
	data/wmf.stl \
	data/ext2.stl \
	data/iso9660.stl \
	data/regf.stl \
	data/rtcp.stl \
	data/pcf.stl \
	data/ppi.stl \
	data/pyc27.stl \
	data/md2.stl \
	data/xm.stl \
	data/protobuf.stl \
	data/bson.stl \
	data/asn1_der.stl \
	data/some_ip.stl \
	data/specpr.stl \
	data/mcap.stl \
	data/minidump.stl \
	data/rsrc.stl \
	data/mov.stl \
	data/snd.stl \
	data/rwstream.stl \
	data/ttf.stl \
	data/macho.stl \
	data/dex.stl \
	data/exif.stl \
	data/rpm.stl \
	data/icc.stl \
	data/dicom.stl \
	data/openpgp.stl \
	data/java_class.stl
