usr/bin/mc
usr/bin/mcedit
usr/bin/mcview
usr/bin/mcdiff
usr/bin/mctree
usr/lib/mc/ext.d/
usr/lib/mc/extfs.d/
usr/lib/mc/cons.saver
usr/lib/mc/mc.csh
usr/lib/mc/mc.fish
usr/lib/mc/mc.sh
usr/lib/mc/mc-wrapper.csh
usr/lib/mc/mc-wrapper.fish
usr/lib/mc/mc-wrapper.sh
etc/mc/
usr/share/doc/mc/LUA_API_REFERENCE.md usr/share/doc/mc6/
usr/share/doc/mc/LUA_PLUGINS.md usr/share/doc/mc6/
usr/share/doc/mc/lua-api.json usr/share/doc/mc6/
